# Generated by Django 5.1.3 on 2024-11-30 19:34

import django.db.models.deletion
import invent_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='location',
            field=models.ForeignKey(default=invent_app.models.get_default_location, on_delete=django.db.models.deletion.CASCADE, to='invent_app.location'),
        ),
    ]
