# Generated by Django 5.1.3 on 2024-12-03 07:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent_app', '0003_accommodation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
